/**
 * Prepare the Next.js static export for Electron packaging.
 * Copies `out/` (generated by `next build` with ELECTRON_BUILD=true) into
 * `app-out/` so that electron-builder can include it as extraResources.
 *
 * No server, no node_modules — just static files served via the app:// protocol.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_SRC = path.join(ROOT, 'out'); // Next.js `output: 'export'` directory
const OUT_DIR = path.join(ROOT, 'app-out'); // Destination copied into the packaged app

function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// ── Validate that the static export was created ───────────────────────────────
if (!fs.existsSync(OUT_SRC)) {
  console.error('ERROR: out/ directory not found.');
  console.error('Make sure to run `next build` with ELECTRON_BUILD=true first.');
  process.exit(1);
}

if (!fs.existsSync(path.join(OUT_SRC, 'index.html'))) {
  console.error('ERROR: out/index.html not found — the Next.js export may have failed.');
  process.exit(1);
}

// ── Clean previous output ─────────────────────────────────────────────────────
if (fs.existsSync(OUT_DIR)) {
  fs.rmSync(OUT_DIR, { recursive: true });
}

// ── Copy export to app-out/ ───────────────────────────────────────────────────
console.log('Copying static export (out/) → app-out/ ...');
copyDirSync(OUT_SRC, OUT_DIR);

const count = fs.readdirSync(OUT_DIR).length;
console.log(`Done! app-out/ is ready for electron-builder (${count} items at root).`);
